accounts/urls.py
from django.conf.urls import url
from accounts import views
from django.contrib.auth.views import logout

urlpatterns = [
    url(r'^send_login_email$', views.send_login_email, name='send_login_email'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', logout, {'next_page': '/'}, name='logout'),
]

lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', views.ViewAndAddToList.as_view(), name='view_list'),
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^users/(.+)/$', views.my_lists, name='my_lists'),
]

superlists/urls.py
from django.conf.urls import url, include
from lists import views
from lists import urls as list_urls
from accounts import urls as accounts_urls

urlpatterns = [
    url(r'^$', views.HomePageView.as_view(), name='home'),
    url(r'^lists/', include(list_urls)),
    url(r'^accounts/', include(accounts_urls)),
]

accounts/models.py
from django.db import models
import uuid
from django.contrib import auth


auth.signals.user_logged_in.disconnect(auth.models.update_last_login)


class User(models.Model):
    email = models.EmailField(primary_key=True)
    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'
    is_anonymous = False
    is_authenticated = True


class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(default=uuid.uuid4, max_length=40)

lists/models.py
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse


class List(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)

    @property
    def name(self):
        return self.item_set.first().text

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

    @staticmethod
    def create_new(first_item_text, owner=None):
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('view_list', args=[self.list.id])

lists/forms.py
from django import forms
from lists.models import Item, List
from django.core.exceptions import ValidationError

EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"


class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control input-lg'
            })
        }
        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR}
        }


class NewListForm(ItemForm):

    def save(self, owner):
        if owner.is_authenticated:
            return List.create_new(
                first_item_text=self.cleaned_data['text'], owner=owner
            )
        else:
            return List.create_new(first_item_text=self.cleaned_data['text'])


class ExistingListItemForm(ItemForm):

    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

accounts/views.py
from django.shortcuts import redirect
from django.core.mail import send_mail
from django.contrib import messages, auth
from accounts.models import Token
from django.urls import reverse


def send_login_email(request):
    email = request.POST['email']
    token = Token.objects.create(email=email)
    url = request.build_absolute_uri(
        reverse('login') + '?token=' + str(token.uid)
    )
    message_body = f'Use this link to log in:\n\n{url}'
    send_mail(
        'Your login link for Superlists',
        message_body,
        'noreply@superlists',
        [email]
    )
    messages.success(
        request,
        "Check your email, we've sent you a link you can use to log in"
    )
    return redirect('/')


def login(request):
    user = auth.authenticate(uid=request.GET.get('token'))
    if user:
        auth.login(request, user)
    return redirect('/')

lists/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
from lists.models import List
from lists.forms import ItemForm, ExistingListItemForm, NewListForm
from django.views.generic import FormView, CreateView, DetailView


User = get_user_model()


class HomePageView(FormView):
    template_name = 'home.html'
    form_class = ItemForm


class ViewAndAddToList(DetailView, CreateView):
    model = List
    template_name = 'list.html'
    form_class = ExistingListItemForm

    def __init__(self):
        super(ViewAndAddToList, self).__init__()
        self.object = None

    def get_form(self, *args, **kwargs):
        self.object = self.get_object()
        return self.form_class(for_list=self.object, data=self.request.POST)


def new_list(request):
    form = NewListForm(data=request.POST)
    if form.is_valid():
        list_ = form.save(owner=request.user)
        return redirect(list_)
    return render(request, 'home.html', {'form': form})


def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, 'my_lists.html', {'owner': owner})

lists/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Your To-Do lists</title>
  </head>
  <body>
		<div class="container">
			<nav class="navbar navbar-default" role="navigation">
				<div class="container-fluid">
					<a href="/" class="navbar-brand">Superlists</a>
					{% if user.email %}
                        <ul class="nav navbar-nav navbar-left">
                            <li><a href="{% url 'my_lists' user.email %}">My lists</a></li>
                        </ul>
						<ul class="nav navbar-nav navbar-right">
							<li class="navbar-text">Logged in as {{ user.email }}</li>
							<li><a href="{% url 'logout' %}">Log out</a></li>
						</ul>
					{% else %}
						<form action="{% url 'send_login_email' %}" method="post" class="navbar-form navbar-right">
							<span>Enter email to login:</span>
							<input name="email" type="text" class="form-control">
							{% csrf_token %}
						</form>
					{% endif %}
				</div>
			</nav>
			{% if messages %}
				<div class="row">
					<div class="col-md-8">
						{% for message in messages %}
							{% if message.level_tag == 'success' %}
								<div class="alert alert-success">{{ message }}</div>
							{% else %}
								<div class="alert alert-warning">{{ message }}</div>
							{% endif %}
						{% endfor %}
					</div>
				</div>
			{% endif %}
			<div class="row justify-content-center">
				<div class="col-md-6 jumbotron">
					<div class="text-center">
						<h1>{% block header_text %}{% endblock header_text %}</h1>
                        {% block list_form %}
                            <form method="post" action="{% block form_action %}{% endblock form_action %}">
                                {% csrf_token %}
                                    {{ form.text }}
                                    {% if form.errors %}
                                        <div class="form-group has-error">
                                            <span class="help-block">{{ form.text.errors }}</span>
                                        </div>
                                    {% endif %}
                            </form>
                        {% endblock list_form %}
					</div>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6">
					{% block table %}
					{% endblock table %}
				</div>
			</div>
            <div class="row justify-content-center">
                <div class="col-md-6">
                    {% block extra_content %}
                    {% endblock extra_content %}
                </div>
            </div>
		</div>

	<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
	<script src="/static/list.js"></script>
	<script>
		$(document).ready(function() {
			window.Superlists.initialize()
		})
	</script>
  </body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock header_text %}

{% block form_action %}{% url 'new_list' %}{% endblock form_action %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock header_text %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock form_action %}

{% block table %}
<table id="id_list_table" class="table">
	{% for item in list.item_set.all %}
		<tr>
			<td>{{ forloop.counter }}: {{ item.text }}</td>
		</tr>
	{% endfor %}
</table>
{% endblock table %}

lists/templates/my_lists.html
{% extends 'base.html' %}

{% block header_text %}My Lists{% endblock header_text %}

{% block list_form %}{% endblock %}

{% block extra_content %}
    <h2>{{ owner.email }}'s lists</h2>
    <ul>
        {% for list in owner.list_set.all %}
            <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock extra_content %}